title: Onassis
author: Author
email: email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the description of my site. For all intents and purposes, it's complete.
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: 'UA-131540516-1' # change this to your GA key
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections_dir: _collections
twitter_username: jekyllrb
github_username: jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed



# Collections configuration
collections:
  articles:
    output: true
  letters:
    output: true
  speeches:
    output: true
  tutorials:
    output: true
